/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daw1.breixo.wordle.gui;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.daw1.breixo.GestorFicheros.IGestorDatos;

/**
 *
 * @author Breixo
 */
public class AnhadirEliminarPalabras extends javax.swing.JDialog {

    /**
     * Creates new form AnhadirEliminarPalabras
     */
    
    private static IGestorDatos gd;
    
    private static int TAMANHO_PALABRA = 5;
    
    private static final java.awt.Color COLOR_VERDE = new java.awt.Color(0, 153, 0);
    private static final java.awt.Color COLOR_ROJO = new java.awt.Color(255, 0, 0);
    
    public AnhadirEliminarPalabras(java.awt.Frame parent, boolean modal,IGestorDatos gf) {
        super(parent, modal);
        gd = gf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainjPanel = new javax.swing.JPanel();
        titulojPanel = new javax.swing.JPanel();
        titulojLabel = new javax.swing.JLabel();
        cuerpojPanel = new javax.swing.JPanel();
        contenedorAnhadirjPanel = new javax.swing.JPanel();
        anhadirjPanel = new javax.swing.JPanel();
        anhadirjTextField = new javax.swing.JTextField();
        anhadirjButton = new javax.swing.JButton();
        mensajeAnhadirjPanel = new javax.swing.JPanel();
        anhadirMensajejLabel = new javax.swing.JLabel();
        contenedorEliminarjPanel = new javax.swing.JPanel();
        eliminarjPanel = new javax.swing.JPanel();
        eliminarjTextField = new javax.swing.JTextField();
        eliminarjButton = new javax.swing.JButton();
        mensajeEliminarjPanel = new javax.swing.JPanel();
        eliminarMensajejLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainjPanel.setLayout(new java.awt.BorderLayout());

        titulojPanel.setLayout(new java.awt.GridBagLayout());

        titulojLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulojLabel.setText("GESTIÓN MOTOR");
        titulojPanel.add(titulojLabel, new java.awt.GridBagConstraints());

        mainjPanel.add(titulojPanel, java.awt.BorderLayout.PAGE_START);

        cuerpojPanel.setLayout(new java.awt.GridLayout(2, 0));

        contenedorAnhadirjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        contenedorAnhadirjPanel.setLayout(new java.awt.GridLayout(2, 0));

        anhadirjTextField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        anhadirjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anhadirjTextField.setPreferredSize(new java.awt.Dimension(160, 23));
        anhadirjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anhadirjTextFieldKeyReleased(evt);
            }
        });
        anhadirjPanel.add(anhadirjTextField);

        anhadirjButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        anhadirjButton.setText("Añadir");
        anhadirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirjButtonActionPerformed(evt);
            }
        });
        anhadirjPanel.add(anhadirjButton);

        contenedorAnhadirjPanel.add(anhadirjPanel);

        mensajeAnhadirjPanel.setLayout(new java.awt.GridBagLayout());

        anhadirMensajejLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        anhadirMensajejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeAnhadirjPanel.add(anhadirMensajejLabel, new java.awt.GridBagConstraints());

        contenedorAnhadirjPanel.add(mensajeAnhadirjPanel);

        cuerpojPanel.add(contenedorAnhadirjPanel);

        contenedorEliminarjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrado palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        contenedorEliminarjPanel.setLayout(new java.awt.GridLayout(2, 0));

        eliminarjTextField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        eliminarjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eliminarjTextField.setPreferredSize(new java.awt.Dimension(160, 23));
        eliminarjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eliminarjTextFieldKeyReleased(evt);
            }
        });
        eliminarjPanel.add(eliminarjTextField);

        eliminarjButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        eliminarjButton.setText("Borrar");
        eliminarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarjButtonActionPerformed(evt);
            }
        });
        eliminarjPanel.add(eliminarjButton);

        contenedorEliminarjPanel.add(eliminarjPanel);

        mensajeEliminarjPanel.setLayout(new java.awt.GridBagLayout());

        eliminarMensajejLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        eliminarMensajejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeEliminarjPanel.add(eliminarMensajejLabel, new java.awt.GridBagConstraints());

        contenedorEliminarjPanel.add(mensajeEliminarjPanel);

        cuerpojPanel.add(contenedorEliminarjPanel);

        mainjPanel.add(cuerpojPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anhadirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirjButtonActionPerformed
        // TODO add your handling code here:
        
        codigoAnhadirPalabra();
        
    }//GEN-LAST:event_anhadirjButtonActionPerformed

    private void eliminarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarjButtonActionPerformed
        // TODO add your handling code here:
        
        codigoEliminarPalabra();
        
    }//GEN-LAST:event_eliminarjButtonActionPerformed

    private void anhadirjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anhadirjTextFieldKeyReleased
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            codigoAnhadirPalabra();
        }
        
    }//GEN-LAST:event_anhadirjTextFieldKeyReleased

    private void eliminarjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarjTextFieldKeyReleased
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            codigoEliminarPalabra();
        }
        
    }//GEN-LAST:event_eliminarjTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnhadirEliminarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnhadirEliminarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnhadirEliminarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnhadirEliminarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnhadirEliminarPalabras dialog = new AnhadirEliminarPalabras(new javax.swing.JFrame(), true,gd);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void codigoEliminarPalabra(){
    
        String palabraEliminar = this.eliminarjTextField.getText().toLowerCase();
        this.eliminarjTextField.setText("");
        this.anhadirMensajejLabel.setText("");
        
        if(palabraEliminar.length() == TAMANHO_PALABRA){
            
            try {
                if(gd.eliminarPalabra(palabraEliminar)){
                    this.eliminarMensajejLabel.setForeground(COLOR_VERDE);
                    this.eliminarMensajejLabel.setText("La palabra se eliminó correctamente");
                }
                else{
                    this.eliminarMensajejLabel.setForeground(COLOR_ROJO);
                    this.eliminarMensajejLabel.setText("La palabra insertada no existe");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Excepción SQL: " + ex.getMessage());
            }
        
        }
        else{
            this.eliminarMensajejLabel.setForeground(COLOR_ROJO);
            this.eliminarMensajejLabel.setText("La palabra a insertar solo puede llevar " + TAMANHO_PALABRA + " letras");
        }
    
    }
    
    private void codigoAnhadirPalabra(){
        
        String palabraAnhadir = this.anhadirjTextField.getText().toLowerCase();
        this.anhadirjTextField.setText("");
        this.eliminarMensajejLabel.setText("");
        
        if(palabraAnhadir.length() == TAMANHO_PALABRA){
            
            if(!gd.existePalabra(palabraAnhadir)){
                try {
                    if(gd.guardarPalabra(palabraAnhadir)){
                        this.anhadirMensajejLabel.setForeground(COLOR_VERDE);
                        this.anhadirMensajejLabel.setText("La palabra se añadió correctamente");
                    }
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Excepción Fichero de Texto: " + ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Excepción SQL: " + ex.getMessage());
                }
            }
            else{
                this.anhadirMensajejLabel.setForeground(COLOR_ROJO);
                this.anhadirMensajejLabel.setText("La palabra insertada ya existe");
            }
        
        }
        else{
            this.anhadirMensajejLabel.setForeground(COLOR_ROJO);
            this.anhadirMensajejLabel.setText("La palabra a insertar solo puede llevar " + TAMANHO_PALABRA + " letras");
        }
    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhadirMensajejLabel;
    private javax.swing.JButton anhadirjButton;
    private javax.swing.JPanel anhadirjPanel;
    private javax.swing.JTextField anhadirjTextField;
    private javax.swing.JPanel contenedorAnhadirjPanel;
    private javax.swing.JPanel contenedorEliminarjPanel;
    private javax.swing.JPanel cuerpojPanel;
    private javax.swing.JLabel eliminarMensajejLabel;
    private javax.swing.JButton eliminarjButton;
    private javax.swing.JPanel eliminarjPanel;
    private javax.swing.JTextField eliminarjTextField;
    private javax.swing.JPanel mainjPanel;
    private javax.swing.JPanel mensajeAnhadirjPanel;
    private javax.swing.JPanel mensajeEliminarjPanel;
    private javax.swing.JLabel titulojLabel;
    private javax.swing.JPanel titulojPanel;
    // End of variables declaration//GEN-END:variables
}
