/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daw1.breixo.wordle.gui;

import java.awt.event.KeyEvent;
import java.io.File;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.daw1.breixo.GestorFicheros.*;

/**
 *
 * @author Breixo
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.awt.Color COLOR_VERDE = new java.awt.Color(0, 153, 0);
    private static final java.awt.Color COLOR_AMARILLO = new java.awt.Color(204, 153, 0);
    private static final java.awt.Color COLOR_ROJO = new java.awt.Color(255, 0, 0);
    
    private static java.util.Set<String> letrasEnVerde = new java.util.TreeSet<>();
    private static java.util.Set<String> letrasEnAmarillo = new java.util.TreeSet<>();
    private static java.util.Set<String> letrasEnRojo = new java.util.TreeSet<>();
    
    private static File FICHERO = new File(Path.of(".") + File.separator + "data" + File.separator + "palabras.txt");
    private static File FICHERO_TXT = new File(Path.of(".") + File.separator + "data" + File.separator + "palabras.txt");
    /*
    Esta será la ruta del fichero de la base de datos
    private static File FICHERO_TXT = new File(Path.of(".") + File.separator + "data" + File.separator + "palabras.txt");
    */
    private static final int MAX_INTENTOS = 6;
    private static final int TAMANHO_PALABRA = 5;
    private static final String CADENA_VACIA = "";
    
    private final javax.swing.JLabel [][] matrizLabels = new javax.swing.JLabel [MAX_INTENTOS][TAMANHO_PALABRA];
    
    private static IGestorDatos gf;
    
    private static int INTENTOS_EN_PARTIDA;
    private String palabraAdivinar;
    
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        
        gf = new GestorFicherosTest();
        initComponents();
        inicializarLabels();
        ocultarLabels();
        //gf = new GestorFicherosTXT(FICHERO);
        INTENTOS_EN_PARTIDA=0;
        palabraAdivinar = gf.cargarPalabraAleatoria();
        
        
    }
    
    
    
    //*** Con este método podemos colorear un laber que escojamos a nuestro gusto ***
    public void colorearLabelYPonerLetra(int fila,int posicion ,java.awt.Color color,String letra){
    
        JLabel[] filaLabels = matrizLabels[fila];//primero escogemos la fila
            
        JLabel jLabel = filaLabels[posicion];//segundo escogemos el Label que queremos colorear
        
        jLabel.setForeground(color);//ponemos el color al Label
        
        jLabel.setText(letra);
        
        jLabel.setVisible(true);// lo ponemos visible
    }
    
    //*** Con este método lo que conseguimos es que desaparezcan las A de los labels y queden ocultas ***
    public void ocultarLabels(){
    
        for (int i = 0; i < matrizLabels.length; i++) {
            JLabel[] filaLabels = matrizLabels[i];
            
            for (int j = 0; j < filaLabels.length; j++) {
                JLabel jLabel = filaLabels[j];
                jLabel.setVisible(false);
            }
        }
    }
    
    //Con este metodo vaciaremos las Labels
    
    public void vaciarLabels(){
    
        for (int i = 0; i < matrizLabels.length; i++) {
            JLabel[] filaLabels = matrizLabels[i];
            
            for (int j = 0; j < filaLabels.length; j++) {
                JLabel jLabel = filaLabels[j];
                jLabel.setText(CADENA_VACIA);
                jLabel.setVisible(false);
            }
        }
    }
    
    
    //*** Con este método lo que conseguimos es meter todas las labels en la misma matriz ***
    public final void inicializarLabels(){
    
        for (int i = 1; i <= MAX_INTENTOS; i++) {
            
            for (int j = 1; j <= TAMANHO_PALABRA; j++) {
                
                try {
                    String nombreLabel = "jLabel" + i + "_" + j;
                    //System.out.println(nombreLabel);
                    
                    javax.swing.JLabel aux = (javax.swing.JLabel)this.getClass().getDeclaredField(nombreLabel).get(this);
                    matrizLabels[i - 1][j - 1] = aux;
                    
                } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
                    Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        modosDeJuegobuttonGroup = new javax.swing.ButtonGroup();
        mainJPanel = new javax.swing.JPanel();
        letrasJPanel = new javax.swing.JPanel();
        jLabel1_1 = new javax.swing.JLabel();
        jLabel1_2 = new javax.swing.JLabel();
        jLabel1_3 = new javax.swing.JLabel();
        jLabel1_4 = new javax.swing.JLabel();
        jLabel1_5 = new javax.swing.JLabel();
        jLabel2_1 = new javax.swing.JLabel();
        jLabel2_2 = new javax.swing.JLabel();
        jLabel2_3 = new javax.swing.JLabel();
        jLabel2_4 = new javax.swing.JLabel();
        jLabel2_5 = new javax.swing.JLabel();
        jLabel3_1 = new javax.swing.JLabel();
        jLabel3_2 = new javax.swing.JLabel();
        jLabel3_3 = new javax.swing.JLabel();
        jLabel3_4 = new javax.swing.JLabel();
        jLabel3_5 = new javax.swing.JLabel();
        jLabel4_1 = new javax.swing.JLabel();
        jLabel4_2 = new javax.swing.JLabel();
        jLabel4_3 = new javax.swing.JLabel();
        jLabel4_4 = new javax.swing.JLabel();
        jLabel4_5 = new javax.swing.JLabel();
        jLabel5_1 = new javax.swing.JLabel();
        jLabel5_2 = new javax.swing.JLabel();
        jLabel5_3 = new javax.swing.JLabel();
        jLabel5_4 = new javax.swing.JLabel();
        jLabel5_5 = new javax.swing.JLabel();
        jLabel6_1 = new javax.swing.JLabel();
        jLabel6_2 = new javax.swing.JLabel();
        jLabel6_3 = new javax.swing.JLabel();
        jLabel6_4 = new javax.swing.JLabel();
        jLabel6_5 = new javax.swing.JLabel();
        bottomJPanel = new javax.swing.JPanel();
        estadoJPanel = new javax.swing.JPanel();
        malJPanel = new javax.swing.JPanel();
        bienJLabel = new javax.swing.JLabel();
        existenJPanel = new javax.swing.JPanel();
        existenJLabel = new javax.swing.JLabel();
        bienJPanel = new javax.swing.JPanel();
        malJLabel = new javax.swing.JLabel();
        inputJPanel = new javax.swing.JPanel();
        palabraJTextField = new javax.swing.JTextField();
        enviarJButton = new javax.swing.JButton();
        exitoJPanel = new javax.swing.JPanel();
        finalJLabel = new javax.swing.JLabel();
        errorJPanel = new javax.swing.JPanel();
        errorJLabel = new javax.swing.JLabel();
        mainjMenuBar = new javax.swing.JMenuBar();
        modoDeJuegojMenu = new javax.swing.JMenu();
        ficheroDeTextojRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        baseDeDatosESjRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        baseDeDatosGLjRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        anhadirEliminarPalabrasjMenuItem = new javax.swing.JMenuItem();
        reiniciarMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAW1 Wordle Breixo");

        mainJPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainJPanel.setLayout(new java.awt.BorderLayout());

        letrasJPanel.setBackground(new java.awt.Color(255, 255, 255));
        letrasJPanel.setLayout(new java.awt.GridLayout(6, 5));

        jLabel1_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_1.setText("A");
        letrasJPanel.add(jLabel1_1);

        jLabel1_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_2.setText("A");
        letrasJPanel.add(jLabel1_2);

        jLabel1_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_3.setText("A");
        letrasJPanel.add(jLabel1_3);

        jLabel1_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_4.setText("A");
        letrasJPanel.add(jLabel1_4);

        jLabel1_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_5.setText("A");
        letrasJPanel.add(jLabel1_5);

        jLabel2_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_1.setText("A");
        letrasJPanel.add(jLabel2_1);

        jLabel2_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_2.setText("A");
        letrasJPanel.add(jLabel2_2);

        jLabel2_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_3.setText("A");
        letrasJPanel.add(jLabel2_3);

        jLabel2_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_4.setText("A");
        letrasJPanel.add(jLabel2_4);

        jLabel2_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_5.setText("A");
        letrasJPanel.add(jLabel2_5);

        jLabel3_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_1.setText("A");
        letrasJPanel.add(jLabel3_1);

        jLabel3_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_2.setText("A");
        letrasJPanel.add(jLabel3_2);

        jLabel3_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_3.setText("A");
        letrasJPanel.add(jLabel3_3);

        jLabel3_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_4.setText("A");
        letrasJPanel.add(jLabel3_4);

        jLabel3_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_5.setText("A");
        letrasJPanel.add(jLabel3_5);

        jLabel4_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_1.setText("A");
        letrasJPanel.add(jLabel4_1);

        jLabel4_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_2.setText("A");
        letrasJPanel.add(jLabel4_2);

        jLabel4_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_3.setText("A");
        letrasJPanel.add(jLabel4_3);

        jLabel4_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_4.setText("A");
        letrasJPanel.add(jLabel4_4);

        jLabel4_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_5.setText("A");
        letrasJPanel.add(jLabel4_5);

        jLabel5_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_1.setText("A");
        letrasJPanel.add(jLabel5_1);

        jLabel5_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_2.setText("A");
        letrasJPanel.add(jLabel5_2);

        jLabel5_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_3.setText("A");
        letrasJPanel.add(jLabel5_3);

        jLabel5_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_4.setText("A");
        letrasJPanel.add(jLabel5_4);

        jLabel5_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_5.setText("A");
        letrasJPanel.add(jLabel5_5);

        jLabel6_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_1.setText("A");
        letrasJPanel.add(jLabel6_1);

        jLabel6_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_2.setText("A");
        letrasJPanel.add(jLabel6_2);

        jLabel6_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_3.setText("A");
        letrasJPanel.add(jLabel6_3);

        jLabel6_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_4.setText("A");
        letrasJPanel.add(jLabel6_4);

        jLabel6_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_5.setText("A");
        letrasJPanel.add(jLabel6_5);

        mainJPanel.add(letrasJPanel, java.awt.BorderLayout.CENTER);

        bottomJPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomJPanel.setPreferredSize(new java.awt.Dimension(200, 100));
        bottomJPanel.setLayout(new java.awt.GridLayout(2, 2));

        estadoJPanel.setBackground(new java.awt.Color(255, 255, 255));
        estadoJPanel.setLayout(new java.awt.GridLayout(3, 1));

        malJPanel.setBackground(new java.awt.Color(255, 255, 255));
        malJPanel.setLayout(new java.awt.GridLayout(1, 0));

        bienJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bienJLabel.setForeground(new java.awt.Color(0, 153, 0));
        bienJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        malJPanel.add(bienJLabel);

        estadoJPanel.add(malJPanel);

        existenJPanel.setBackground(new java.awt.Color(255, 255, 255));
        existenJPanel.setLayout(new java.awt.GridLayout(1, 0));

        existenJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        existenJLabel.setForeground(new java.awt.Color(204, 153, 0));
        existenJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        existenJPanel.add(existenJLabel);

        estadoJPanel.add(existenJPanel);

        bienJPanel.setBackground(new java.awt.Color(255, 255, 255));
        bienJPanel.setLayout(new java.awt.GridLayout(1, 0));

        malJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        malJLabel.setForeground(new java.awt.Color(255, 0, 0));
        malJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bienJPanel.add(malJLabel);

        estadoJPanel.add(bienJPanel);

        bottomJPanel.add(estadoJPanel);

        inputJPanel.setBackground(new java.awt.Color(255, 255, 255));

        palabraJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        palabraJTextField.setPreferredSize(new java.awt.Dimension(120, 23));
        palabraJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                palabraJTextFieldKeyReleased(evt);
            }
        });
        inputJPanel.add(palabraJTextField);

        enviarJButton.setText("Enviar");
        enviarJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarJButtonActionPerformed(evt);
            }
        });
        inputJPanel.add(enviarJButton);

        bottomJPanel.add(inputJPanel);

        exitoJPanel.setBackground(new java.awt.Color(255, 255, 255));
        exitoJPanel.setLayout(new java.awt.GridBagLayout());

        finalJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        finalJLabel.setForeground(new java.awt.Color(51, 153, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 99, 18, 99);
        exitoJPanel.add(finalJLabel, gridBagConstraints);

        bottomJPanel.add(exitoJPanel);

        errorJPanel.setBackground(new java.awt.Color(255, 255, 255));
        errorJPanel.setLayout(new java.awt.GridBagLayout());

        errorJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorJLabel.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 106, 18, 107);
        errorJPanel.add(errorJLabel, gridBagConstraints);

        bottomJPanel.add(errorJPanel);

        mainJPanel.add(bottomJPanel, java.awt.BorderLayout.PAGE_END);

        modoDeJuegojMenu.setText("Opciones");
        modoDeJuegojMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        modosDeJuegobuttonGroup.add(ficheroDeTextojRadioButtonMenuItem);
        ficheroDeTextojRadioButtonMenuItem.setSelected(true);
        ficheroDeTextojRadioButtonMenuItem.setText("Fichero de texto");
        ficheroDeTextojRadioButtonMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ficheroDeTextojRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheroDeTextojRadioButtonMenuItemActionPerformed(evt);
            }
        });
        modoDeJuegojMenu.add(ficheroDeTextojRadioButtonMenuItem);

        modosDeJuegobuttonGroup.add(baseDeDatosESjRadioButtonMenuItem);
        baseDeDatosESjRadioButtonMenuItem.setText("Base de datos ES");
        baseDeDatosESjRadioButtonMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baseDeDatosESjRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseDeDatosESjRadioButtonMenuItemActionPerformed(evt);
            }
        });
        modoDeJuegojMenu.add(baseDeDatosESjRadioButtonMenuItem);

        modosDeJuegobuttonGroup.add(baseDeDatosGLjRadioButtonMenuItem);
        baseDeDatosGLjRadioButtonMenuItem.setText("Base de datos GL");
        baseDeDatosGLjRadioButtonMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baseDeDatosGLjRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseDeDatosGLjRadioButtonMenuItemActionPerformed(evt);
            }
        });
        modoDeJuegojMenu.add(baseDeDatosGLjRadioButtonMenuItem);

        anhadirEliminarPalabrasjMenuItem.setText("Añadir/Eliminar Palabras");
        anhadirEliminarPalabrasjMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anhadirEliminarPalabrasjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirEliminarPalabrasjMenuItemActionPerformed(evt);
            }
        });
        modoDeJuegojMenu.add(anhadirEliminarPalabrasjMenuItem);

        reiniciarMenuItem.setText("Reiniciar");
        reiniciarMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reiniciarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarMenuItemActionPerformed(evt);
            }
        });
        modoDeJuegojMenu.add(reiniciarMenuItem);

        mainjMenuBar.add(modoDeJuegojMenu);

        setJMenuBar(mainjMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ficheroDeTextojRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheroDeTextojRadioButtonMenuItemActionPerformed
        seleccionarConversor();
        reiniciarProgram();
    }//GEN-LAST:event_ficheroDeTextojRadioButtonMenuItemActionPerformed

    private void baseDeDatosESjRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseDeDatosESjRadioButtonMenuItemActionPerformed
        seleccionarConversor();
        reiniciarProgram();
    }//GEN-LAST:event_baseDeDatosESjRadioButtonMenuItemActionPerformed

    private void reiniciarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarMenuItemActionPerformed
        // TODO add your handling code here:
        reiniciarProgram();
        
    }//GEN-LAST:event_reiniciarMenuItemActionPerformed

    private void anhadirEliminarPalabrasjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirEliminarPalabrasjMenuItemActionPerformed
        // TODO add your handling code here:
        
        AnhadirEliminarPalabras dialog = new AnhadirEliminarPalabras(this,true,gf);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_anhadirEliminarPalabrasjMenuItemActionPerformed

    private void enviarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarJButtonActionPerformed
        codigoFuncionamientoPanelCentral();
    }//GEN-LAST:event_enviarJButtonActionPerformed

    private void palabraJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_palabraJTextFieldKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            codigoFuncionamientoPanelCentral();
        }
    }//GEN-LAST:event_palabraJTextFieldKeyReleased

    private void baseDeDatosGLjRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseDeDatosGLjRadioButtonMenuItemActionPerformed
        seleccionarConversor();
        reiniciarProgram();
    }//GEN-LAST:event_baseDeDatosGLjRadioButtonMenuItemActionPerformed

    private void codigoFuncionamientoPanelCentral(){
    
        String palabra = this.palabraJTextField.getText().toLowerCase();
        
        int contadorLetrasAcertadas = 0;

        if(palabra.length() == TAMANHO_PALABRA){
            
            quitarErrorPalabras();
        
            java.awt.Color colorearDe;

            for (int i = 0; i < TAMANHO_PALABRA; i++) {
                int printColor = gf.comprobarCaracter(i, palabraAdivinar, palabra);
                
                String ponerLetra = palabra.substring(0 + i, 1 + i).toUpperCase();
                
                String viewVerde;
                String viewAmarillo;
                String viewRojo;

                if (printColor == 1) {
                    colorearDe = COLOR_VERDE;
                    contadorLetrasAcertadas++;
                    
                    letrasEnVerde.add(ponerLetra);
                    
                    if(letrasEnAmarillo.contains(ponerLetra)){
                        letrasEnAmarillo.remove(ponerLetra);
                        viewAmarillo = limpiarCorchetesSet(letrasEnAmarillo.toString());
                        this.existenJLabel.setText(viewAmarillo);
                    }
                    viewVerde = limpiarCorchetesSet(letrasEnVerde.toString());
                    this.bienJLabel.setText(viewVerde);
                } else if (printColor == 0) {
                    colorearDe = COLOR_AMARILLO;
                    if(!letrasEnVerde.contains(ponerLetra)){
                        letrasEnAmarillo.add(ponerLetra);
                    }
                    viewAmarillo = limpiarCorchetesSet(letrasEnAmarillo.toString());
                    this.existenJLabel.setText(viewAmarillo);
                } else {
                    colorearDe = COLOR_ROJO;
                    
                    letrasEnRojo.add(ponerLetra);
                    viewRojo = limpiarCorchetesSet(letrasEnRojo.toString());
                    this.malJLabel.setText(viewRojo);
                }

                colorearLabelYPonerLetra(INTENTOS_EN_PARTIDA, i, colorearDe, ponerLetra);
            }
            
            INTENTOS_EN_PARTIDA++;
            
            if(contadorLetrasAcertadas == TAMANHO_PALABRA){
            
                this.palabraJTextField.setEnabled(false);
                this.finalJLabel.setForeground(COLOR_VERDE);
                this.finalJLabel.setText("Enhorabuena, has ganado en " + INTENTOS_EN_PARTIDA + " intentos");
            }
            else if(INTENTOS_EN_PARTIDA == 6){

                this.palabraJTextField.setEnabled(false);
                this.finalJLabel.setForeground(COLOR_ROJO);
                this.finalJLabel.setText("Que pena, la palabra era " + palabraAdivinar.toUpperCase());
            }
            
        }
        else{
            ponerErrorPalabras();
        }
    
    }
    
    private void reiniciarProgram(){
    
        vaciarLabels();
        INTENTOS_EN_PARTIDA = 0;
        palabraAdivinar = gf.cargarPalabraAleatoria();
        this.palabraJTextField.setEnabled(true);
        this.finalJLabel.setText(CADENA_VACIA);
        letrasEnVerde.clear();
        this.bienJLabel.setText(CADENA_VACIA);
        letrasEnAmarillo.clear();
        this.existenJLabel.setText(CADENA_VACIA);
        letrasEnRojo.clear();
        this.malJLabel.setText(CADENA_VACIA);
    }
    
    private void ponerErrorPalabras(){
        
        this.errorJPanel.setVisible(true);
        this.errorJLabel.setVisible(true);
        this.errorJLabel.setText("La palabra debe de contener 5 letras");
        this.palabraJTextField.setText(CADENA_VACIA);
    }
    
    private void quitarErrorPalabras(){
        
        this.errorJPanel.setVisible(false);
        this.errorJLabel.setVisible(false);
        this.errorJLabel.setText(CADENA_VACIA);
        this.palabraJTextField.setText(CADENA_VACIA);
    }
    
    private String limpiarCorchetesSet(String c) {

        StringBuilder sb = new StringBuilder(c);
        
        sb = sb.delete(0, 1);

        sb = sb.delete(sb.length()-1, sb.length());
        
        return sb.toString();
    }
    
    private void seleccionarConversor(){
    
        if(this.ficheroDeTextojRadioButtonMenuItem.isSelected()){
            FICHERO = FICHERO_TXT;
            gf = new GestorFicherosTXT(FICHERO);
        }
        else if(this.baseDeDatosESjRadioButtonMenuItem.isSelected()){
            gf = new GestorFicherosBaseDatos("es");
        }
        else if(this.baseDeDatosGLjRadioButtonMenuItem.isSelected()){
            gf = new GestorFicherosBaseDatos("gl");
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anhadirEliminarPalabrasjMenuItem;
    private javax.swing.JRadioButtonMenuItem baseDeDatosESjRadioButtonMenuItem;
    private javax.swing.JRadioButtonMenuItem baseDeDatosGLjRadioButtonMenuItem;
    private javax.swing.JLabel bienJLabel;
    private javax.swing.JPanel bienJPanel;
    private javax.swing.JPanel bottomJPanel;
    private javax.swing.JButton enviarJButton;
    private javax.swing.JLabel errorJLabel;
    private javax.swing.JPanel errorJPanel;
    private javax.swing.JPanel estadoJPanel;
    private javax.swing.JLabel existenJLabel;
    private javax.swing.JPanel existenJPanel;
    private javax.swing.JPanel exitoJPanel;
    private javax.swing.JRadioButtonMenuItem ficheroDeTextojRadioButtonMenuItem;
    private javax.swing.JLabel finalJLabel;
    private javax.swing.JPanel inputJPanel;
    private javax.swing.JLabel jLabel1_1;
    private javax.swing.JLabel jLabel1_2;
    private javax.swing.JLabel jLabel1_3;
    private javax.swing.JLabel jLabel1_4;
    private javax.swing.JLabel jLabel1_5;
    private javax.swing.JLabel jLabel2_1;
    private javax.swing.JLabel jLabel2_2;
    private javax.swing.JLabel jLabel2_3;
    private javax.swing.JLabel jLabel2_4;
    private javax.swing.JLabel jLabel2_5;
    private javax.swing.JLabel jLabel3_1;
    private javax.swing.JLabel jLabel3_2;
    private javax.swing.JLabel jLabel3_3;
    private javax.swing.JLabel jLabel3_4;
    private javax.swing.JLabel jLabel3_5;
    private javax.swing.JLabel jLabel4_1;
    private javax.swing.JLabel jLabel4_2;
    private javax.swing.JLabel jLabel4_3;
    private javax.swing.JLabel jLabel4_4;
    private javax.swing.JLabel jLabel4_5;
    private javax.swing.JLabel jLabel5_1;
    private javax.swing.JLabel jLabel5_2;
    private javax.swing.JLabel jLabel5_3;
    private javax.swing.JLabel jLabel5_4;
    private javax.swing.JLabel jLabel5_5;
    private javax.swing.JLabel jLabel6_1;
    private javax.swing.JLabel jLabel6_2;
    private javax.swing.JLabel jLabel6_3;
    private javax.swing.JLabel jLabel6_4;
    private javax.swing.JLabel jLabel6_5;
    private javax.swing.JPanel letrasJPanel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JMenuBar mainjMenuBar;
    private javax.swing.JLabel malJLabel;
    private javax.swing.JPanel malJPanel;
    private javax.swing.JMenu modoDeJuegojMenu;
    private javax.swing.ButtonGroup modosDeJuegobuttonGroup;
    private javax.swing.JTextField palabraJTextField;
    private javax.swing.JMenuItem reiniciarMenuItem;
    // End of variables declaration//GEN-END:variables
}
